GET https://localhost:8080/comment

###

POST https://localhost:8080/comment
Content-Type: application/json

###

GET https://localhost:8080/user/

###
GET https://localhost:8080/user/5

###

POST https://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "name": "wilhelm",
    "password": "mem"
}