spring:
    profiles:
        active: 
    datasource:
        url: jdbc:h2:mem:sandbox
        driverClassName: org.h2.Driver  
        username: willpine
        password: willpine
    
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect  
        hibernate:
            ddl-auto: update

    h2:
        console:
            enabled: true
---
spring:
    config:
        activate:
            on-profile: https
server:
    ssl:
        key-store-type: PKCS12
        key-store: classpath:keystore.p12
        key-store-password: willpine
        key-alias: devtomcat
        key-password: willpine